extends Node

#General
enum RACES{DRAGONBORN = 0, DWARF, ELF, GNOME, HALF_ELF, HALFLING, HALF_ORC, HUMAN, TIEFLING}

enum ETHICS {LAWFUL = 0, NEUTRAL, CHAOTIC}
enum MORALS {GOOD = 0, NEUTRAL, EVIL}

enum TYPES {UNKNOWN = -1, RANDOM, ABERRATION, BEAST, CELESTIAL, CONSTRUCT, DRAGON, ELEMENTAL, FEY, FIEND, GIANT, HUMANOID, MONSTROSITY, OOZE, PLANT, UNDEAD}

enum DMG_ELEMENTS {NORMAL = -1, ACID = 0, COLD, FIRE, FORCE, LIGHTNING, NECROTIC, POISON, PSYCHIC, RADIANT, THUNDER}

enum DMG_TYPES {MISC = -1, BLUDGEONING = 0, PIERCING, SLASHING}

enum DICE_TYPES {MISC = -1, MELEE = 0, RANGED, GUARD, EVADE, C_MELEE, C_RANGED, C_GUARD, C_EVADE};

#Player
enum CLASSES{BARBARIAN = 0, BARD, CLERIC, DRUID, FIGHTER, MONK, PALADIN, RANGER, ROGUE, SORCERER, WARLOCK, WIZARD}
